include ../../XX/Makefile.rules


test1: part1
	@echo "expected: 0, 3, 2, 31"
	@./$< < ../test1.txt

puzzle1: part1
	@echo "puzzle result:"
	@./$< < ../puzzle1.txt


test2: part2
	@echo "expected: 806"
	@./$< < ../test2.txt

puzzle2: part2
	@echo "puzzle result:"
	@./$< < ../puzzle1.txt
