include ../../XX/Makefile.rules


test1: part1
	@echo "expected: 5587"
	@time ./$< < ../test1.txt

puzzle1: part1
	@echo "puzzle result:"
	@time ./$< < ../puzzle1.txt

test2: part2
	@echo "expected: 2511944"
	@time ./$< < ../test1.txt

puzzle2: part2
	@echo "puzzle result:"
	@time ./$< < ../puzzle1.txt
