include ../../XX/Makefile.rules


test1: part1
	@echo "expected: 2"
	@./$< < ../test1.txt

puzzle1: part1
	@echo "puzzle result:"
	@./$< < ../puzzle1.txt


test2: part2
	@echo "expected: 3"
	@./$< < ../test2.txt

puzzle2: part2
	@echo "puzzle result:"
	@./$< < ../puzzle1.txt
