include ../../XX/Makefile.rules


test1: part1
	@echo "expected: 24"
	@time ./$< < ../test1.txt

puzzle1: part1
	@echo "puzzle result:"
	@time ./$< < ../puzzle1.txt

puzzle2: part2
	@echo "puzzle result:"
	@time ./$< < ../puzzle1.txt
