include ../../XX/Makefile.rules


test1:
	@echo "expected: 18"
	@awk -f part1.awk < ../test1.txt

puzzle1: 
	@echo "puzzle result:"
	@awk -f part1.awk < ../puzzle.txt


test2:
	@echo "expected: 9"
	@awk -f part2.awk < ../test2.txt

puzzle2:
	@echo "puzzle result:"
	@awk -f part2.awk < ../puzzle.txt
