include ../../XX/Makefile.rules


test1: part1
	@echo "expected: 18"
	@./$< < ../test1.txt

puzzle1: part1
	@echo "puzzle result:"
	@./$< < ../puzzle.txt


test2: part2
	@echo "expected: 9"
	@./$< < ../test2.txt

puzzle2: part2
	@echo "puzzle result:"
	@./$< < ../puzzle.txt
