include ../../XX/Makefile.rules


test1: part1
	@echo "expected: 5"
	@./$< < ../test1.txt

puzzle1: part1
	@echo "puzzle result:"
	@./$< < ../puzzle1.txt


test2: part2
	@echo "expected: 10"
	@./$< < ../test1.txt

puzzle2: part2
	@echo "puzzle result:"
	@./$< < ../puzzle1.txt
