include ../../XX/Makefile.rules


test1: part1
	@echo "expected results: 3, 4, 0, 9"
	@./$< < ../test1.txt

puzzle1: part1
	@echo "puzzle result:"
	@./$< < ../puzzle.txt


test2: part2
	@echo "expected results: 6, 0, 4, 12, 4"
	@./$< < ../test2.txt

puzzle2: part2
	@echo "puzzle result:"
	@./$< < ../puzzle.txt
